// Generated by Wrangler on Mon Jun 10 2024 13:53:34 GMT+0900 (대한민국 표준시)
// by running `wrangler types`

interface Env {
	cache: KVNamespace;
	COOKIE_SESSION_SECRET: string;
	HONEYPOT_SECRET: string;
	CSRF_SECRET: string;
	TOAST_SECRET: string;
	API_BASE_URL: string;
	SENTRY_DSN: string;
}
