// Generated by Wrangler on Thu May 30 2024 10:48:10 GMT+0900 (대한민국 표준시)
// by running `wrangler types`

interface Env {
	cache: KVNamespace;
	COOKIE_SESSION_SECRET: string;
	HONEYPOT_SECRET: string;
	CSRF_SECRET: string;
	TOAST_SECRET: string;
	API_BASE_URL: string;
	CF_ID: string;
	CF_API_TOKEN: string;
}
